server:
  port: 8080
spring:
  application:
    name: blog_system_1
  profiles:
    active: dev
  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/blogdb
      database: blogdb