spring:
  data:
    mongodb:
      #uri: mongodb://admin:pass@mongodb:27017
      database: blog
      host: localhost
      port: 27017
      username: user
      password: pass
      authentication-database: blog
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Enable SQL logging to debug database connectivity issues:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      #default_schema: public  # Primary schema
      #temp:
      #  use_jdbc_metadata_defaults: false
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
  sql:
    init:
      mode: always  # Runs SQL scripts on startup (schema.sql, data.sql)
  devtools:
    restart:
      additional-paths: src/main/java # setup which directory to restart
      additional-exclude: static/**,public/** # exclude the directory
      enabled: true # warm-startup the springboor project
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Berlin
    default-property-inclusion: non_null

  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      # classpath: it stands for the target directory of the project
      # /upload/ without classpath in the beginning. It indicates the path where the webserver tomcat runs
      static-locations: classpath:/css/, classpath:/js/, classpath:/images/, classpath:/static/, /upload/
  mvc:
    static-path-pattern: /images/**
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.example.blog_system.entity
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    path: logs