
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    hostname: mongodb-hostname
    restart: always
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
      - mongo_log:/var/log/mongodb
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
    networks:
      - my_network
    ports:
      - 27017:27017

  postgres:
    image: postgres:latest
    container_name: postgres-container
    hostname: postgres-hostname
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/data/db
      - postgres_log:/var/log/postgres
      - ./postgres-entrypoint:/docker-entrypoint-initdb.d
    networks:
      - my_network
    ports:
      - 5433:5432  # Mapping container's internal port 5432 to host 5433

  blogsystem:
    container_name: blogsystem-container
    build:
      context: ./springboot-project/.
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - spring.data.mongodb.host=mongodb
      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - mongodb
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
    name: mongo_data
  mongo_log:
    driver: local
    name: mongo_log
  postgres_data:
    driver: local
    name: postgres_data
  postgres_log:
    driver: local
    name: postgres_log
